# Generated by Django 4.2.5 on 2023-09-12 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_books', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id Books')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('realease_year', models.IntegerField(verbose_name='Release Year')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('pages', models.IntegerField(verbose_name='Pages')),
                ('publishing_company', models.CharField(max_length=255, verbose_name='Publishing Company')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
